### ISSUE TITLE
Access forbidden for files in IC repo

### ISSUE THREAD

**Issue by farrell236** [HPCE/hpce-2014-cw2#1]
I get access forbidden when trying to access any files from this directory:

http://cas.ee.ic.ac.uk/people/dt10/teaching/2013/hpce/cw2/

**Comment by m8pple** [comment]
So to confirm, you're saying the command:

```
curl http://cas.ee.ic.ac.uk/people/dt10/teaching/2013/hpce/cw2/sox-14.4.1.tar.gz -o packages/sox-14.4.1.tar.gz
```

doesn't work?

Or are you saying you can't download it in a web browser?

**Comment by farrell236** [comment]
![screen shot 2015-01-25 at 15 19 51](https://cloud.githubusercontent.com/assets/9416769/5891934/bc58a9c0-a4a5-11e4-9b33-15bcbf6de7f0.png)

This is what happens when I run the command

**Comment by m8pple** [comment]
The error message is saying that it is failing to create the local file, not that it can't download it,
so it appears to be failing client side.

It looks like you're running it from the home directory, rather than a directory resulting from
the `git clone`. Is there a directory called `packages` for it to write the file into?

If you are running the command outside the project directory, you could modify it to:

```
curl http://cas.ee.ic.ac.uk/people/dt10/teaching/2013/hpce/cw2/sox-14.4.1.tar.gz -o sox-14.4.1.tar.gz
```

(i.e. drop the packages directory from the output file).

**Comment by farrell236** [comment]
Ahh I see my mistake, I didn't see the 2 spaces on either side of "-o". I assumed it was one long URL to the file location. Thanks Dr Thomas.

**Comment by m8pple** [comment]
No problem, it's part of the idea of this coursework - to get people back in (or into) the command line habit so they can use hardware on remote servers later on.

And I appreciate people going through the steps early - let me know if you see any other problems.
