### ISSUE TITLE
Automating build: Error finding dir for ./configure prefix

### ISSUE THREAD

**Issue by chungcyk** [HPCE/hpce-2014-cw2#16]
When I'm trying to automate the build from my makefile, I've been getting error while making both sox and lame. It seems like the $(pwd) thing is not working since it's trying to get to "../../local" from the folder root. I have also tried $(shell pwd) as suggested by @txsl and the internet.. But no luck :/ Any suggestions?

![image](https://cloud.githubusercontent.com/assets/5358463/6010159/1548c348-ab28-11e4-9ff9-b6a3f1169c40.png) 
(Windows 8, cygwin)

**Comment by yuchen-w** [comment]
Try running Cygwin with administrator privileges. It worked for me.

Sent from Outlook

On Mon, Feb 2, 2015 at 2:11 PM -0800, "Michael Chung" notifications@github.com wrote:
When I'm trying to automate the build from my makefile, I've been getting error while making both sox and lame. It seems like the $(pwd) thing is not working since it's trying to get to "../../local" from my root. I have also tried $(shell pwd) as suggested by @txsl and the internet.. But no luck :/ Any suggestions?

![image](https://cloud.githubusercontent.com/assets/5358463/6010159/1548c348-ab28-11e4-9ff9-b6a3f1169c40.png)
(Windows 8, cygwin)

---

Reply to this email directly or view it on GitHub:
https://github.com/HPCE/hpce-2014-cw2/issues/16

**Comment by chungcyk** [comment]
It was just a silly typo I made - thanks :)
