### ISSUE TITLE
Stopping script when stdin is empty

### ISSUE THREAD

**Issue by salmanarif** [HPCE/hpce-2014-cw2#20]
When using `time (./mp3_file_src.sh <filename> | ./corrupter.sh | ./all_firs_direct.sh > /dev/null )` in the "Some benchmarking" section, the script `corrupter.sh` runs indefinitely, even after the input file has been completely processed.

I'm thinking `signal_generator` is the culprit here since it can run indefinitely. Is there a way to detect when `stdin` becomes empty in to stop `signal_generator`?

**Comment by m8pple** [comment]
What should normally happen is that whenever an up-stream channel runs out of data (end of file),
then the it causes that filter to finish and send EOF, causing the next filter to finish, and so on.

If corruptor.sh is not terminating, I would be suspicious of the merge function: if one input stream
stops supplying data, does it notice that and stop processing?

A simple test would be something like:

```
./merge \
    <(cat /dev/zero | head -c 1024) \
    <(cat /dev/zero) \
> /dev/null
```

(I'd also try with the streams swapped, to check there isn't a bias for the first or second stream).

The first stream will stop after 1024 bytes, while the second one is infinite. Does the merge operator
notice one of the streams has finished? The [read](http://linux.die.net/man/2/read) documentation
says that it will return 0 bytes read on end of file, so that is one way of telling.

**Comment by darioml** [comment]
@m8pple Shouldn't merge want 512 samples, i.e. 2024 bytes?

```
./merge \
    <(cat /dev/zero | head -c 4096) \
    <(cat /dev/zero) \
> /dev/null
```

**Comment by m8pple** [comment]
True, 2048 bytes would give merge exactly 512 samples (one buffer full), but even if it only
gets a quarter of a buffer it should still notice that one of the streams has come to an end
(whether it exits gracefully or treats it as an error it should exit).

**Comment by salmanarif** [comment]
@m8pple Fixed now using end of file detection. Thank you!
