### ISSUE TITLE
Compiling Lame

### ISSUE THREAD

**Issue by bwh10** [HPCE/hpce-2014-cw2#4]
I originally could not compile Lame but this is a well known solved issue: http://www.linuxfromscratch.org/blfs/view/svn/multimedia/lame.html

It only happens for those running on i686 with GNU 4.9.0+ compilers. 

The configuration should instead be set as follows in the command line and lame will compile fine:

sed -i -e '/xmmintrin.h/d' configure

./configure --prefix="$(pwd)/../../local" --enable-mp3rtp --disable-static 

Took me quite a while to fix this non assessed issue so perhaps it should be included in the readme file?

**Comment by m8pple** [comment]
Thanks, that's extremely useful. It seems that all four of my linux/cygwin test platforms are
still sub 4.9, as I'm on stable/older distros.

I'll apply the patch in place, as I don't want to increase complexity of the install,
but I'll need to try and check it doesn't cause regressions on down-level compilers
first.

For now, I'll link to the issue from the readme.

Again, thank you for describing the problem, and producing the solution.

**Comment by m8pple** [comment]
Ok, I've reproduced under i686 with 4.9.2.

While the above solution appears to work, I found a solution which appears
to be less invasive (I'm reluctant to `sed` out lines due to future compatability
worries) and still allows good performance on other archs:

```
./configure --prefix="$(pwd)/../../local" CPPFLAGS=-march=native
```

This tells the compiler to target the processor it is currently running on, which in
pretty much all cases will have xmm intrinsics available. Plus, in the spirit
of the course, we should try to allow the compiler to apply vectorisation if it can :)

So that is my suggestion to others as something to try,but @bwh10, your
solution is perfectly fine to use as well.
