### ISSUE TITLE
Minor Issue: time command does not have any arguments

### ISSUE THREAD

**Issue by AugustineTan** [HPCE/hpce-2014-cw2#7]
the command
`time -f %e cat /dev/zero | head -c 1000000 | ./passthrough 2 > /dev/null`

returns

```
-bash: -f: command not found

real    0m0.101s
user    0m0.015s
sys     0m0.062s
```

I have found the man page for time but no matter what options I try it always says not found.

**Comment by m8pple** [comment]
Ah, my fault. The problem is that `time` is a [bash builtin](http://www.gnu.org/software/bash/manual/html_node/Bash-Builtins.html), while there is also a standard unix program called [`time`](http://man7.org/linux/man-pages/man1/time.1.html).

The second one takes arguments, but the first one gets used by default. I forgot that I have aliases
installed on the machine where I developed and tested the coursework.

You can find out where the actual time is by doing:

```
which time
```

It will probably be in either `/bin/time` or `/usr/bin/time`, but it is difficult to predict.
On some machines it may need to be installed via a package manager (for example,
cygwin64).

You can then do:

```
/bin/time -f %e cat /dev/zero | head -c 1000000 | ./passthrough $n > /dev/null
```

or:

```
/bin/usr/time -f %e cat /dev/zero | head -c 1000000 | ./passthrough $n > /dev/null
```
